name: sber_pay_android
description: Android implementation of the sber_pay plugin
version: 3.1.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: sber_pay
    platforms:
      android:
        package: plugin.sdk
        pluginClass: SberPayPlugin
        dartPluginClass: SberPayAndroid

dependencies:
  flutter:
    sdk: flutter
  sber_pay_platform_interface:
    path: ../sber_pay_platform_interface
dev_dependencies:
  pigeon: ^26.0.0
  flutter_lints: ^6.0.0
